config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
  	member do
      get :following, :followers
    end
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  root to: 'home#top'
  get 'home/about' => 'home#about'
  get "search" => "users#search"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
   has_many :followers, through: :passive_relationships, source: :follower
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

    # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
 

  def User.search(search, user_or_book, how_search)
        if user_or_book == "1"
            if how_search == "1"
                    User.where(['name LIKE ?', "%#{search}%"])
            elsif how_search == "2"
                    User.where(['name LIKE ?', "%#{search}"])
            elsif how_search == "3"
                    User.where(['name LIKE ?', "#{search}%"])
            elsif how_search == "4"
                    User.where(['name LIKE ?', "#{search}"])
            else
                    User.all
            end
         end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
      before_action :authenticate_user!
	    before_action :baria_user,{only: [:edit,:update]}

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end
  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render :edit
  	end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).reverse_order
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).reverse_order
    render 'show_follow'
  end
  def search
    @user_or_book = params[:option]
    @how_search = params[:choice]
    if @user_or_book == "1"
       @users = User.search(params[:search], @user_or_book, @how_search)
    else
      @books = Book.search(params[:search], @user_or_book, @how_search)
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :search)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
    @user = User.find(params[:id])
  	if @user != current_user
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<% if user.id != current_user.id %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn follow_btn" %>
  <% end %>
  <% else %>
   <%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-success follow_btn" %>
<% end %>
  <% end %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<% @user ||= current_user %>
		<tr>
  			<th>follows</th>
  			<th><a href="<%= following_user_path(@user) %>">
   			 <strong id="following" class="stat">
     		 <%= user.following.count %>
    		</strong></a>
    		</th>
    	</tr>
 	    <tr>
 	    	<th>followers</th>
  			<th><a href="<%= followers_user_path(@user) %>">
   			 <strong id="followers" class="stat">
     		 <%= user.followers.count %>
   			 </strong>
 			 </a></th>
		</tr>
</table>
<%= render 'users/follow_form', user: @user %>

<div class="row">
<% if user.id == current_user.id %>
	<%= link_to '',edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>

</div>
	<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="4"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td>フォロー数:　<%= user.following.count %></td>
 	    	<td>フォロワー数:　<%= user.followers.count %></td>
			<td><% if user.id != current_user.id %>
				  <div id="follow_form">
				  <% if current_user.following?(user) %>
				    <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
				  <%= f.submit "Unfollow", class: "btn follow_btn" %>
				  <% end %>
				  <% else %>
				   <%= form_for(current_user.active_relationships.build) do |f| %>
				  <div><%= hidden_field_tag :followed_id, user.id %></div>
				  <%= f.submit "Follow", class: "btn btn-success follow_btn" %>
				<% end %>
				  <% end %>
				  </div>
				<% end %>
				</td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->
</div>
</div>

app/views/users/search.html.erb
<% if @user_or_book == "1"%>
    <h1>User search</h1>
<table class="table">
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="4"></th>
        </tr>
    </thead>
        <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
            <td><%= user.name%></td>
            <td>フォロー数:　<%= user.following.count %></td>
            <td>フォロワー数:　<%= user.followers.count %></td>
            <td><% if user.id != current_user.id %>
                  <div id="follow_form">
                  <% if current_user.following?(user) %>
                    <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
                  <%= f.submit "Unfollow", class: "btn follow_btn" %>
                  <% end %>
                  <% else %>
                   <%= form_for(current_user.active_relationships.build) do |f| %>
                  <div><%= hidden_field_tag :followed_id, user.id %></div>
                  <%= f.submit "Follow", class: "btn btn-success follow_btn" %>
                <% end %>
                  <% end %>
                  </div>
                <% end %>
                </td>
            <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
        </tbody>
    </table>


<% elsif @user_or_book == "2" %>
    <h2>Book search</h2>
    <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                </tr>
            </thead>

            <tbody>
                <% @books.each do |book| %>
                <tr>
                    <td>
                        <%= link_to(book.user) do %>
                        <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
                        <% end %>
                    </td>
                    <td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
                    <td><%= book.body %></td>
                    <% if book.favorited_by?(current_user) %>
                    <td>
                        <%= link_to book_favorites_path(book.id), method: :delete do %>
                        <i class="fa fa-heart" style="color: red;"></i>
                        <%= book.favorites.count %>
                    <% end %>
                    </td>
                    <% else %>
                    <td>
                        <%= link_to book_favorites_path(book.id),method: :post do %>
                        <i class="fa fa-heart"></i>
                        <%= book.favorites.count %>
                    <% end %>
                    </td>
                    <% end %>
                    <td>
                        <i class="fa fa-comments"></i>
                        <%= book.book_comments.count %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
<% else %>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<% if book.favorited_by?(current_user) %>
					<td>
						<%= link_to book_favorites_path(book.id), method: :delete do %>
						<i class="fa fa-heart" style="color: red;"></i>
						<%= book.favorites.count %>
					<% end %>
					</td>
					<% else %>
					<td>
						<%= link_to book_favorites_path(book.id),method: :post do %>
						<i class="fa fa-heart"></i>
						<%= book.favorites.count %>
					<% end %>
					</td>
					<% end %>
					<td>
						<i class="fa fa-comments"></i>
						<%= book.book_comments.count %>
					</td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--books一覧 -->

</div>
</div>

app/views/users/show_follow.html.erb
<% if @users.any? %>
		<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="4"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td>フォロー数:　<%= user.following.count %></td>
 	    	<td>フォロワー数:　<%= user.followers.count %></td>
			<td><% if user.id != current_user.id %>
				  <div id="follow_form">
				  <% if current_user.following?(user) %>
				    <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
				  <%= f.submit "Unfollow", class: "btn follow_btn" %>
				  <% end %>
				  <% else %>
				   <%= form_for(current_user.active_relationships.build) do |f| %>
				  <div><%= hidden_field_tag :followed_id, user.id %></div>
				  <%= f.submit "Follow", class: "btn btn-success follow_btn" %>
				<% end %>
				  <% end %>
				  </div>
				<% end %>
				</td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
		<% end %>