config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
  	member do
      get :following, :followers
    end
  end
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resource :book_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  root to: 'home#top'
  get 'home/about' => 'home#about'
  get "search" => "users#search"
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, optional: true
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
		def favorited_by?(user)
			favorites.where(user_id: user.id).exists?
		end

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def Book.search(search, user_or_book, how_search)
        if how_search == "1"
            Book.where(['title LIKE ?', "%#{search}%"])
        elsif how_search == "2"
            Book.where(['title LIKE ?', "%#{search}"])
        elsif how_search == "3"
            Book.where(['title LIKE ?', "#{search}%"])
        elsif how_search == "4"
            Book.where(['title LIKE ?', "#{search}"])
        else
            Book.all
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
      before_action :authenticate_user!
      before_action :baria_user,{only: [:edit,:update,:destroy]}
  def show
  	@book = Book.find(params[:id])
    @books = Book.new
    @book_comment = BookComment.new
    @favorite = Favorite.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
  def baria_user
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
   end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<% if book.favorited_by?(current_user) %>
					<td>
						<%= link_to book_favorites_path(book.id), method: :delete do %>
						<i class="fa fa-heart" style="color: red;"></i>
						<%= book.favorites.count %>
					<% end %>
					</td>
					<% else %>
					<td>
						<%= link_to book_favorites_path(book.id),method: :post do %>
						<i class="fa fa-heart"></i>
						<%= book.favorites.count %>
					<% end %>
					</td>
					<% end %>
					<td>
						<i class="fa fa-comments"></i>
						<%= book.book_comments.count %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @books %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book%></td>
					<td><%= @book.body %></td>
					<% if @book.user.id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book}" %></td>
					<% end %>

					<% if @book.favorited_by?(current_user) %>
					<td>
						<%= link_to book_favorites_path(@book), method: :delete do %>
						<i class="fa fa-heart" style="color: red;"></i>
						<%= @book.favorites.count %>
					<% end %>
					</td>
					<% else %>
					<td>
						<%= link_to book_favorites_path(@book), method: :post do %>
						<i class="fa fa-heart"></i>
						<%= @book.favorites.count %>
					<% end %>
					</td>
					<% end %>
					<td>
						<i class="fa fa-comment"></i>
						<%= @book.book_comments.count %>
					</td>
				</tr>
			</table>
	<ul>
		<% @book.book_comments.each do |book_comment| %>
		<li class="comment row">
				<%= link_to (book_comment.user) do %>
						<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= book_comment.user.name %>
						<% end %>
			<div class="comment-body">
				<p class="comment-txt">
					<%= book_comment.comment %>
				</p>
				<% if current_user == book_comment.user %>
				<p><%= link_to "Destroy",book_book_comments_path(book_comment.book, book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book_comment}" %></p>
			</div>
				<% end %>
		</li>
		<% end %>
	</ul>
	<div class="comment-form">
			<%= form_for [@book, @book_comment] do |f| %>
	<% if @book_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_comment.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="field row">
		<%= f.text_area :comment, class: "col-xs-11 book_body" %>
	</div>
	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-11" %>
	</div>
<% end %>
</div>
	</div>
</div>